tination: ./_site
auto:        true
lsi:         false
server_port: 4000
pygments:    true
markdown:    redcarpet
permalink:   date
redcarpet:
  fenced_code_blocks: true
  strikethrough: true
  superscript: true
  underline: true
  highlight: true
  footnotes: true
