destination: ./_site
auto:        true
lsi:         false
server_port: 4000
pygments:    true
markdown:    redcarpet
permalink:   date
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]
